name: "qwen3-vl"
backend: "python"
max_batch_size: 4

input [
  {
    name: "message"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "image"
    data_type: TYPE_STRING
    dims: [ -1 ]
    optional: true
  }
]

output [
  {
    name: "response"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "response_time"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]

dynamic_batching {
  preferred_batch_size: [ 4 ]
  max_queue_delay_microseconds: 100
}
